version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_ENTRYPOINT_QUITE_LOGS=1
    depends_on:
      - server
      - web

  db:
    container_name: db
    image: postgres
    volumes:
      - .data/postgresql:/var/lib/postgresql/data
    env_file:
      - .env.dev

  server:
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    volumes:
      - ./server:/src
    env_file:
      - .env.dev
    depends_on:
      - db

  web:
    container_name: web
    build: ./web
    stdin_open: true
    tty: true
    volumes:
      - ./web:/src
    depends_on:
      - server
      - db
